require("sabbir.plugins-setup")
require("sabbir.core.options")
require("sabbir.core.keymaps")
require("sabbir.core.colorscheme")
require("sabbir.plugins.comment")
require("sabbir.plugins.nvim-tree")
require("sabbir.plugins.lualine")
require("sabbir.plugins.telescope")
require("sabbir.plugins.nvim-cmp")
require("sabbir.plugins.lsp.mason")
-- require("sabbir.plugins.lsp.lspsaga")
require("sabbir.plugins.lsp.lspconfig")
require("sabbir.plugins.lsp.null-ls")
require("sabbir.plugins.autopairs")
require("sabbir.plugins.treesitter")
require("sabbir.plugins.gitsigns")
